// <auto-generated />
namespace Project4thYear.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class NewIDAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewIDAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "201504020930342_NewIDAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
